### ISSUE TITLE
Heart rate stalls, Fitbit Sense

### ISSUE THREAD

**Issue by KyleNERD** [aidanblack/Fitbit-ClassicClock#4] opened 2021-07-12 21:39 UTC
Sometimes the heart rate on the watch face stalls on the Fitbit Sense.  The heart icon continues to flash, but the digits don’t update to reflect the current heart rate.  Switching apps on the watch doesn’t restart it.  The Fitbit “today” app seems unaffected.

After a few hours it seems to start showing live heart rate readings again.  Very odd.

**Comment by aidanblack** [comment] 2021-07-12 22:17
Thanks! I've seen this intermittently but not frequently enough to be able to catch the cause. I think sometimes it just doesn't register that the watch is on your wrist. I'll do some more digging and update this issue with any progress.

**Comment by aidanblack** [comment] 2021-07-13 20:58
https://github.com/aidanblack/Fitbit-ClassicClock/commit/f588c2b1df6cd01e9abe0d749ecf4edd5e25722b commit will try to address this. Waiting for approval in the Fitbit Gallery.

After the update is approved, please close this issue if the bug is fixed.

**Comment by KyleNERD** [comment] 2021-07-13 23:50
@aidanblack thanks for looking into this.  It’s a great watch face.

I hear you.  Intermittent bugs are the the worst to chase down.  I like your changes to index.js.  Worth a shot.

**Comment by aidanblack** [comment] 2021-07-15 13:50
The update has been approved. Select the watch face in the Fitbit app to download the update. I will leave these two issues open for now - let me know if the issue appears to be fixed. Thanks for the feedback!

**Closed as completed** 2022-08-18 13:36 UTC
Labels: bug
